# PDFNet Default Configuration

model:
  name: PDFNet_swinB
  input_size: 1024
  drop_path: 0.1
  pretrained_swin: checkpoints/swin_base_patch4_window12_384_22k.pth

training:
  # Basic settings
  batch_size: 1
  epochs: 100
  num_workers: 8
  seed: 0

  # Optimizer
  optimizer: adamw
  lr: 1.0e-4
  weight_decay: 0.05
  momentum: 0.9
  betas: [0.9, 0.999]
  eps: 1.0e-8

  # Scheduler
  scheduler: cosine
  warmup_epochs: 5
  min_lr: 1.0e-5
  warmup_lr: 1.0e-6

  # Gradient
  clip_grad: null
  update_freq: 1

  # Mixed precision
  use_amp: true

  # Checkpointing
  save_freq: 1
  keep_best: 3

  # Evaluation
  eval_metric: F1
  eval_freq: 1

  # Augmentation
  augment: true
  color_jitter: 0.4
  mixup: 0.8
  cutmix: 1.0

data:
  dataset: DIS
  root_path: DATA/DIS-DATA
  train_split: DIS-TR
  val_split: DIS-VD
  test_splits:
    - DIS-TE1
    - DIS-TE2
    - DIS-TE3
    - DIS-TE4

  # Image settings
  input_size: 1024
  normalize_mean: [0.485, 0.456, 0.406]
  normalize_std: [0.229, 0.224, 0.225]

  # Cache settings
  cache_data: false
  cache_dir: cache/

inference:
  checkpoint_path: checkpoints/PDFNet_Best.pth
  batch_size: 1
  use_tta: false
  tta_scales: [0.75, 1.0, 1.25]
  device: cuda

  # MoGe depth settings
  use_moge: true
  moge_model: checkpoints/moge/moge-2-vitl-normal/model.pt
  moge_input_size: 518

output:
  save_dir: runs
  log_dir: logs
  checkpoint_dir: checkpoints
  result_dir: results

logging:
  use_tensorboard: true
  log_freq: 10
  verbose: true

# Environment
device: cuda
distributed: false
world_size: 1
local_rank: -1